/**
 * Copyright @ 2015-2018 重庆中科云丛科技有限公司  All Rights Reserved.
 *
 * This file is automatically generated by MyBatis Generator, do not modify.
 * MyBatis Generator was modified by FUNDSTAR team, if you have any questions please contact with author.
 * Project Name: FundStar
 * File Name: User.java
 * Creat Date: 2015-08-15 11:30:16
 */
package com.timo.xml;

import java.io.Serializable;
import java.util.Date;

/**
 * Class Name: User<br/>
 * Description: This class corresponds to the table - FND_USER<br>
 * Create Date: 2015-08-15 11:30:16 <br/>
 */
public class User implements Serializable {
	


	/**
	 * serialVersionUID:序列化ID,缓存需要
	 */
	private static final long serialVersionUID = -5737387281932315813L;
	
	public User() {

	}

	/**
	 * FND_USER.USER_ID 用户ID
	 */
	private String userId;

	/**
	 * FND_USER.DEPT_CODE 部门代码
	 */
	private String deptCode;
	/**
	 * ORG_LEVEL 机构级别(数据字典)
	 */
	private String orgLevel;
	/**
	 * 部门名称
	 */
	private String deptName;

	/**
	 * FND_USER.WORK_CODE 用户员工号
	 */
	private String workCode;

	/**
	 * 机构编码
	 */
	private String orgCode;
	
	/**
	 * 机构编码全路径
	 */
	private String orgCodePath;
	
	/**
	 * 法人机构编码全路径
	 */
	private String legalOrgCode;
	
	/**
	 * 法人机构编码
	 */
	private String legalCode;

	/**
	 * 机构名称
	 */
	private String orgName;
	
	/**
	 * 机构全名称
	 */
	private String orgAName;

	/**
	 * FND_USER.USER_LOGIN_NAME 用户登录名
	 */
	private String userLoginName;

	/**
	 * FND_USER.USER_PWD 口令
	 */
	private String userPwd;

	/**
	 * FND_USER.USER_STATUS 用户状态(1 正常 2 暂停 3首次登录)
	 */
	private Integer userStatus;

	/**
	 * FND_USER.USER_NAME 全名
	 */
	private String userName;

	/**
	 * FND_USER.USER_RANK 职位
	 */
	private String userRank;

	/**
	 * FND_USER.EMAIL 邮箱
	 */
	private String email;

	/**
	 * FND_USER.TELEPHONE 联系电话
	 */
	private String telephone;

	/**
	 * FND_USER.PICTURE_NAME 照片名称
	 */
	private String pictureName;
	
	/**
	 * FND_USER.PICTURE_NAME 照片名称
	 */
	private String pictureOne;
	
	/**
	 * FND_USER.PICTURE_NAME 照片名称
	 */
	private String pictureTwo;
	
	/**
	 * FND_USER.PICTURE_NAME 照片名称
	 */
	private String pictureThree;
	
	/**
	 * FND_USER.FEATURE 1:1特征
	 */  
	private String ifeature;
	
	/**
	 * FND_USER.NFEATURE 1：n特征
	 */  
	private String nfeature;
	
	/**
	 * MAC地址
	 */
	private String macAddress;

	/**
	 * FND_USER.REMARK 备注
	 */
	private String remark;

	/**
	 * FND_USER.CREATE_DATE 创建日期
	 */
	private Date createDate;

	/**
	 * FND_USER.UPDATE_DATE 修改日期
	 */
	private Date updateDate;

	/**
	 * FND_USER.DELETE_DATE 注销时间
	 */
	private Date deleteDate;

	/**
	 * 机构名称
	 */
	private String roleName;

	public String getUserId() {
		return userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public String getDeptCode() {
		return deptCode;
	}

	public void setDeptCode(String deptCode) {
		this.deptCode = deptCode;
	}

	public String getOrgLevel() {
		return orgLevel;
	}

	public void setOrgLevel(String orgLevel) {
		this.orgLevel = orgLevel;
	}

	public String getDeptName() {
		return deptName;
	}

	public void setDeptName(String deptName) {
		this.deptName = deptName;
	}

	public String getWorkCode() {
		return workCode;
	}

	public void setWorkCode(String workCode) {
		this.workCode = workCode;
	}

	public String getOrgCode() {
		return orgCode;
	}

	public void setOrgCode(String orgCode) {
		this.orgCode = orgCode;
	}

	public String getOrgCodePath() {
		return orgCodePath;
	}

	public void setOrgCodePath(String orgCodePath) {
		this.orgCodePath = orgCodePath;
	}

	public String getLegalOrgCode() {
		return legalOrgCode;
	}

	public void setLegalOrgCode(String legalOrgCode) {
		this.legalOrgCode = legalOrgCode;
	}

	public String getLegalCode() {
		return legalCode;
	}

	public void setLegalCode(String legalCode) {
		this.legalCode = legalCode;
	}

	public String getOrgName() {
		return orgName;
	}

	public void setOrgName(String orgName) {
		this.orgName = orgName;
	}

	public String getOrgAName() {
		return orgAName;
	}

	public void setOrgAName(String orgAName) {
		this.orgAName = orgAName;
	}

	public String getUserLoginName() {
		return userLoginName;
	}

	public void setUserLoginName(String userLoginName) {
		this.userLoginName = userLoginName;
	}

	public String getUserPwd() {
		return userPwd;
	}

	public void setUserPwd(String userPwd) {
		this.userPwd = userPwd;
	}

	public Integer getUserStatus() {
		return userStatus;
	}

	public void setUserStatus(Integer userStatus) {
		this.userStatus = userStatus;
	}

	public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getUserRank() {
		return userRank;
	}

	public void setUserRank(String userRank) {
		this.userRank = userRank;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getTelephone() {
		return telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	public String getPictureName() {
		return pictureName;
	}

	public void setPictureName(String pictureName) {
		this.pictureName = pictureName;
	}

	public String getPictureOne() {
		return pictureOne;
	}

	public void setPictureOne(String pictureOne) {
		this.pictureOne = pictureOne;
	}

	public String getPictureTwo() {
		return pictureTwo;
	}

	public void setPictureTwo(String pictureTwo) {
		this.pictureTwo = pictureTwo;
	}

	public String getPictureThree() {
		return pictureThree;
	}

	public void setPictureThree(String pictureThree) {
		this.pictureThree = pictureThree;
	}

	public String getIfeature() {
		return ifeature;
	}

	public void setIfeature(String ifeature) {
		this.ifeature = ifeature;
	}

	public String getNfeature() {
		return nfeature;
	}

	public void setNfeature(String nfeature) {
		this.nfeature = nfeature;
	}

	public String getMacAddress() {
		return macAddress;
	}

	public void setMacAddress(String macAddress) {
		this.macAddress = macAddress;
	}

	public String getRemark() {
		return remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public Date getCreateDate() {
		return createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Date getUpdateDate() {
		return updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	public Date getDeleteDate() {
		return deleteDate;
	}

	public void setDeleteDate(Date deleteDate) {
		this.deleteDate = deleteDate;
	}

	public String getRoleName() {
		return roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}
}